FROM node:26-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 5173

# Run the development server and bind it to all network interfaces
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]